#!/usr/bin/env python3
"""
Draw the futhorc wordmark for the Android splash screen.

Android vector drawables cannot render text, and the splash screen is drawn by
the system before any app code runs - so there is no font to fall back on and no
Compose to lay anything out. The runes are emitted as stroke paths instead,
taken from the same polylines the app teaches you to write. The splash and the
lessons therefore cannot disagree about a shape.

ᚠᚢᚦᚩᚱᚳ is an acrostic, not a spelling: the alphabet is named after its first six
runes - feoh, ur, thorn, os, rad, cen - the way "alphabet" comes from alpha and
beta. Spelling it out phonetically would be wrong, and has been once already.

    python3 scripts/genwordmark.py

Writes app/src/main/res/drawable/splash_wordmark.xml in the Android project.
Run it again after scripts/genglyphs.py changes any of those six shapes.
"""
import json
from pathlib import Path

WORD = 'ᚠᚢᚦᚩᚱᚳ'
GAP = 14.0        # between runes, in glyph units (a glyph is 100 tall)
PAD = 8.0         # around the whole word, so strokes aren't clipped
INK = '#F7F4EF'   # the pale of the launcher mark, which reads on the dark splash

HERE = Path(__file__).resolve().parent.parent
DATA = HERE / 'android-data' / 'futhorc-data.json'
OUT = (HERE.parent.parent / 'AndroidApps' / 'Futhorc' / 'app' / 'src' / 'main'
       / 'res' / 'drawable' / 'splash_wordmark.xml')


def main():
    glyphs = json.loads(DATA.read_text())['glyphs']

    # Lay the runes out left to right in one coordinate space.
    xs, total = [], 0.0
    for r in WORD:
        xs.append(total)
        total += glyphs[r]['w'] + GAP
    total -= GAP

    vw, vh = total + PAD * 2, 100 + PAD * 2

    paths = []
    for r, x0 in zip(WORD, xs):
        for stroke in glyphs[r]['strokes']:
            pts = [(x0 + PAD + px, PAD + py) for px, py in stroke]
            d = f'M{pts[0][0]:.2f},{pts[0][1]:.2f}' + ''.join(
                f'L{x:.2f},{y:.2f}' for x, y in pts[1:])
            paths.append(d)

    body = '\n'.join(
        f'    <path\n'
        f'        android:pathData="{d}"\n'
        f'        android:strokeColor="{INK}"\n'
        f'        android:strokeWidth="6"\n'
        f'        android:strokeLineCap="round"\n'
        f'        android:strokeLineJoin="round" />'
        for d in paths)

    # The system splash clips its icon to a circle: 192dp across when no icon
    # background colour is set. A 3.9:1 banner fits inside that at about
    # 186x48dp, so the drawable declares a size that already fits rather than
    # relying on whoever writes the layer-list to work the trigonometry out.
    dp_w = 96.0
    dp_h = dp_w * vh / vw

    OUT.write_text(f'''<?xml version="1.0" encoding="utf-8"?>
<!--
    AUTO-GENERATED by the web project's scripts/genwordmark.py - do not edit.

    ᚠᚢᚦᚩᚱᚳ, drawn from the same stroke polylines the app teaches you to write.
    An acrostic: the alphabet is named after its first six runes.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{dp_w:.0f}dp"
    android:height="{dp_h:.0f}dp"
    android:viewportWidth="{vw:.2f}"
    android:viewportHeight="{vh:.2f}">
{body}
</vector>
''')
    print(f'{OUT.name}: {len(paths)} stroke paths from {len(WORD)} runes, '
          f'viewport {vw:.0f}x{vh:.0f}, drawn at {dp_w:.0f}x{dp_h:.0f}dp')


if __name__ == '__main__':
    main()
